# Generated by Django 3.1 on 2020-11-08 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=250)),
                ('city', models.PositiveIntegerField()),
                ('postal_code', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', smartfields.fields.ImageField(upload_to='item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maddi_app.category')),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=250)),
                ('destination_city', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('message', models.TextField()),
                ('cancellation', models.SmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maddi_app.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maddi_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maddi_app.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('date_paid', models.DateTimeField()),
                ('method', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maddi_app.purchase')),
            ],
        ),
    ]
